[package]
name = "parse_sample_counts"
version = "0.1.0"
authors = ["swamyvs <swamyvinny@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.8"
clap = "2.33.3"
