---
title: "Metadata Extraction Examples"
output: html_notebook
---

```{r}
library(tidyverse)
library(recount3)

url_SRP163355_meta <- locate_url(
  "SRP163355",
  "data_sources/sra"
)
local_SRP163355_meta <- file_retrieve(
  url = url_SRP163355_meta
)

## Read the metadata
SRP163355_meta <- read_metadata(local_SRP163355_meta)

```

Now that we have pulled the metadata we can now extract the study specific sample info. From experience the most 
useful field is **usually** `sra.experiment_title`

```{r}
custom_meta <- SRP163355_meta %>% 
  mutate(name = external_id,
         condition = str_extract(sra.experiment_title, '\\w+\\d*rep') %>% 
           gsub('rep','',.)) %>% 
  select(name, condition)
custom_meta %>% sample_n(10)
```

Print it for use in the plotting script
```{r}
write_tsv(custom_meta, file = 'SRP163355_meta.tsv', col_names = FALSE)
```

Grab the data for plotting

This will take several minutes
```{R}
gene <- c("PRX$") 
source('../src/r3_data_puller.R')
SRP163355_gene <- r3_data_puller(type = 'gene', 
                                 study_accession = 'SRP163355', 
                                 meta = meta, 
                                 gene = gene, 
                                 organism = 'human')

SRP163355_exon <- r3_data_puller(type = 'exon', 
                                 study_accession = 'SRP163355', 
                                 meta = meta, 
                                 gene = gene, 
                                 organism = 'human')

library(snapcount)
sb <- QueryBuilder(compilation="gtex", regions="PRX")
prx_gtex_gene <- query_gene(sb)
prx_gtex_exon <- query_exon(sb)

```

# Gene Plot
```{r}
SRP163355_gene %>% 
  filter(gene_name == 'PRX') %>% 
  ggplot(aes(x=Condition, y=log2(value+1), fill = Condition)) +
  geom_boxplot() +
  theme_cowplot() +
  guides(x =  guide_axis(angle = 90)) +
  scale_fill_manual(values = c(pals::brewer.set1(n=12), pals::brewer.set2(n=10)) %>% unname()) +
  xlab('Condition') + 
  facet_wrap(~gene_name, ncol = 5, scales = 'free_x')
```

# Add in GTEx
```{r}

```